We start by testing libraries and checking if the dataset loads properly.

In [6]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

TwitchData = pd.read_csv("twitchdata-update.csv")

#Replacing spaces for underscores and removing parentheses from column names to prevent issues with functions.
TwitchData.columns = TwitchData.columns.str.replace(" ", "_")
TwitchData.columns = TwitchData.columns.str.replace("(", "").str.replace(")", "")

#check first parts of our dataset.
TwitchData.head()

,Channel,Watch_timeMinutes,Stream_timeminutes,Peak_viewers,Average_viewers,Followers,Followers_gained,Views_gained,Partnered,Mature,Language
0,xQcOW,6196161750,215250,222720,27716,3246298,1734810,93036735,True,False,English
1,summit1g,6091677300,211845,310998,25610,5310163,1370184,89705964,True,False,English
2,Gaules,5644590915,515280,387315,10976,1767635,1023779,102611607,True,True,Portuguese
3,ESL_CSGO,3970318140,517740,300575,7714,3944850,703986,106546942,True,False,English
4,Tfue,3671000070,123660,285644,29602,8938903,2068424,78998587,True,False,English

Once Our file is properly read and uploaded we check for the details like any missing informations:

In [13]:
TwitchData.shape
TwitchData.info()
TwitchData.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Channel             1000 non-null   object
 1   Watch_timeMinutes   1000 non-null   int64
 2   Stream_timeminutes  1000 non-null   int64
 3   Peak_viewers        1000 non-null   int64
 4   Average_viewers     1000 non-null   int64
 5   Followers           1000 non-null   int64
 6   Followers_gained    1000 non-null   int64
 7   Views_gained        1000 non-null   int64
 8   Partnered           1000 non-null   bool
 9   Mature              1000 non-null   bool
 10  Language            1000 non-null   object
dtypes: bool(2), int64(7), object(2)
memory usage: 72.4+ KB

,Watch_timeMinutes,Stream_timeminutes,Peak_viewers,Average_viewers,Followers,Followers_gained,Views_gained
count,1.000000e+03,1000.000000,1000.000000,1000.000000,1.000000e+03,1.000000e+03,1.000000e+03
mean,4.184279e+08,120515.160000,37065.051000,4781.040000,5.700541e+05,2.055185e+05,1.166817e+07
std,5.496355e+08,85376.201364,60314.307686,8453.684965,8.044134e+05,3.399137e+05,2.490572e+07
min,1.221928e+08,3465.000000,496.000000,235.000000,3.660000e+03,-1.577200e+04,1.757880e+05
25%,1.631899e+08,73758.750000,9113.750000,1457.750000,1.705462e+05,4.375825e+04,3.880602e+06
50%,2.349908e+08,108240.000000,16676.000000,2425.000000,3.180630e+05,9.835200e+04,6.456324e+06
75%,4.337399e+08,141843.750000,37569.750000,4786.250000,6.243322e+05,2.361308e+05,1.219676e+07
max,6.196162e+09,521445.000000,639375.000000,147643.000000,8.938903e+06,3.966525e+06,6.701375e+08