In [22]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://www.ccny.cuny.edu/registrar/fall"
response = requests.get(url)

In [23]:
soup = BeautifulSoup(response.text, "html.parser")
table = soup.find("table")
rows = table.find_all("tr")
print("Number of rows:", len(rows))

Number of rows: 37

In [24]:
data = []
for row in rows[1:]:
    cols = row.find_all("td")
    if len(cols) >= 3:
        date_str = cols[0].get_text(strip=True)
        dow_str  = cols[1].get_text(strip=True)
        text_str = cols[2].get_text(strip=True)
        data.append([date_str, dow_str, text_str])
print(data[:3])

[['August 01', 'Sunday', 'Application for degree for January and February 2022 begins'], ['August 18', 'Wednesday', 'Last day to apply for Study Abroad'], ['August 24', 'Tuesday', 'Last day of Registration;Last day to file ePermit for the Fall 2021;Last day to drop classes for 100% tuition refund;']]

In [25]:
df = pd.DataFrame(data, columns=["date", "dow", "text"])
df.head()

,date,dow,text
0,August 01,Sunday,Application for degree for January and Februar...
1,August 18,Wednesday,Last day to apply for Study Abroad
2,August 24,Tuesday,Last day of Registration;Last day to file ePer...
3,August 25,Wednesday,Start of Fall Term;Classes begin;Initial Regis...
4,August 25 - 31,Wednesday - Tuesday,Change of program period; late fees apply

In [26]:
clean_dates = []
for d in df["date"]:
    d = d.replace(",", "")
    d = d.split("-")[0].strip()

    if ("2021" not in d) and ("2022" not in d):
        d = d + " 2021"
    clean_dates.append(pd.to_datetime(d))

df["date"] = clean_dates
df.head()

,date,dow,text
0,2021-08-01,Sunday,Application for degree for January and Februar...
1,2021-08-18,Wednesday,Last day to apply for Study Abroad
2,2021-08-24,Tuesday,Last day of Registration;Last day to file ePer...
3,2021-08-25,Wednesday,Start of Fall Term;Classes begin;Initial Regis...
4,2021-08-25,Wednesday - Tuesday,Change of program period; late fees apply